# Generated by Django 5.1.4 on 2024-12-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('driver_lat', models.FloatField()),
                ('driver_lng', models.FloatField()),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car')], max_length=4)),
                ('distance', models.FloatField(null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('rating', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
